source/source/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('select2/', include('django_select2.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

source/webapp/urls.py
from django.urls import path

from webapp.views.skils import SkillDetailView, SkillUpdateView, SkillCreateView, SkillSearchView, delete_skill
from webapp.views.child import ChildList, ChildSearchView, ChildDetailView, ChildUpdateView, ChildCreateView, \
    soft_delete_child
from webapp.views.program import ProgramDetailView, ProgramListView, ProgramCreateView, ProgramUpdateView, \
    ProgramSearchView, ChildInProgramListView
from webapp.views.categories import CategoriesListView, CategoriesDetailView, CategoriesCreateView, \
    CategoriesUpdateView, CategoriesSearchView, delete_category
from webapp.views.session import create_session_and_result, AddExtraSkill, counter_get_view, counter_done, \
    counter_done_with_hint
from webapp.views.result import change_status_skill, ResultUpdateView, ResultListView, close_session_result_view

app_name = 'webapp'

urlpatterns = [
    # counter urls------------------------------------------------------------------------------------------------
    path('skill_w_hint/<int:pk>', counter_done_with_hint, name='done_w_hint'),
    path('skill_done/<int:pk>', counter_done, name='counter_done'),
    path('get_skills/<int:pk>', counter_get_view, name='counter_get_view'),
    # child urls--------------------------------------------------------------------------------------------------
    path('child/', ChildList.as_view(), name='child_list'),
    path('child_search/', ChildSearchView.as_view(), name='search_view'),
    path('child/<int:pk>', ChildDetailView.as_view(), name='child_detail'),
    path('child/create', ChildCreateView.as_view(), name='child_create'),
    path('child/<int:pk>/update', ChildUpdateView.as_view(), name='child_update'),
    path('child/<int:pk>/delete', soft_delete_child, name='child_delete'),
    # program urls------------------------------------------------------------------------------------------------
    path('', ChildInProgramListView.as_view(), name='child_program_list'),
    path('program/', ProgramListView.as_view(), name='program_list'),
    path('program_search/', ProgramSearchView.as_view(), name='search_view_program'),
    path('program/<int:pk>', ProgramDetailView.as_view(), name='program_detail'),
    path('program/create', ProgramCreateView.as_view(), name='program_create'),
    path('program/<int:pk>/update', ProgramUpdateView.as_view(), name='program_update'),
    # category urls-----------------------------------------------------------------------------------------------
    path('categories/', CategoriesListView.as_view(), name='categories_list'),
    path('categories/<int:pk>', CategoriesDetailView.as_view(), name='categories_detail'),
    path('categories/create', CategoriesCreateView.as_view(), name='categories_create'),
    path('categories/<int:pk>/update', CategoriesUpdateView.as_view(), name='categories_update'),
    path('categories/<int:pk>/delete', delete_category, name='categories_delete'),
    path('categories/categories_search/', CategoriesSearchView.as_view(), name='search_view_categories'),
    # session_urls------------------------------------------------------------------------------------------------
    path('program/<int:pk>/session', create_session_and_result, name='session_create'),
    path('program/<int:pk>/skill/create', AddExtraSkill.as_view(), name='extra_skill'),
    # result_urls------------------------------------------------------------------------------------------------
    path('session/<int:pk>/result', ResultListView.as_view(), name='session_result_view'),
    path('session/<int:pk>', close_session_result_view, name='change_status_session'),
    path('skill_in_program/<int:pk>', change_status_skill, name='change_status_skill'),
    path('session/result/<int:pk>/update', ResultUpdateView.as_view(), name='session_result_update'),
    # skill urls--------------------------------------------------------------------------------------------------
    path('skill/<int:pk>', SkillDetailView.as_view(), name='skill_detail'),
    path('skill/create', SkillCreateView.as_view(), name='skill_create'),
    path('skill/<int:pk>/update', SkillUpdateView.as_view(), name='skill_update'),
    path('skill/<int:pk>/delete', delete_skill, name='skill_delete'),
    path('skill/skill_search/', SkillSearchView.as_view(), name='search_view_skill')
]

source/webapp/models.py
from django.db import models
from django.contrib.auth.models import User


class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT, related_name='client', verbose_name='Пользователь')
    phone = models.CharField(max_length=50, verbose_name='Телефон пользователя')
    child = models.ManyToManyField('Child', related_name='user_child', verbose_name='Ребенок')
    deleted_date = models.DateTimeField(null=True, blank=True, verbose_name='Дата удаления')
    edited_date = models.DateTimeField(auto_now=True, blank=True, null=True, verbose_name='Дата редактирования')

    def __str__(self):
        return "%s" % self.user.username


class SoftDeleteManager(models.Manager):
    def active(self):
        return self.filter(is_deleted=False)

    def deleted(self):
        return self.filter(is_deleted=True)


class Child(models.Model):
    first_name = models.CharField(max_length=100, verbose_name='Имя ребенка')
    last_name = models.CharField(max_length=100, verbose_name='Фамилия ребенка')
    third_name = models.CharField(max_length=100, blank=True, null=True, verbose_name='Отчество ребенка')
    birthday = models.DateField(blank=True, null=True, verbose_name='Дата рождения')
    age = models.CharField(max_length=100, verbose_name='Возраст')
    address = models.TextField(max_length=1000, blank=True, null=True, verbose_name='Адрес проживания')
    characteristic = models.CharField(max_length=1000, blank=True, null=True, verbose_name='Характеристика на ребенка')
    preferences = models.CharField(max_length=1000, blank=True, null=True, verbose_name='Предпочтения ребенка')
    first_parent = models.CharField(max_length=255, verbose_name='Родитель')
    second_parent = models.CharField(max_length=255, blank=True, null=True, verbose_name='Второй родитель')
    contacts = models.CharField(max_length=200, blank=True, null=True, verbose_name='Контакты ребенка')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления ребенка')
    edited_date = models.DateTimeField(auto_now=True, null=True, blank=True, verbose_name='Дата редактирования')
    deleted_date = models.DateTimeField(null=True, blank=True, verbose_name='Дата удаления')
    is_deleted = models.BooleanField(default=False)

    objects = SoftDeleteManager()

    def __str__(self):
        return "%s %s" % (self.first_name, self.last_name)

    class Meta:
        verbose_name = 'Дети'
        verbose_name_plural = 'Дети'


class Categories(models.Model):
    name = models.CharField(max_length=255, verbose_name='Название категории')
    code_category = models.CharField(max_length=50, null=True, blank=True, verbose_name='Код категории')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')
    edited_date = models.DateTimeField(auto_now=True, null=True, blank=True, verbose_name='Время редактирования')
    deleted_date = models.DateTimeField(null=True, blank=True, verbose_name='Время удаления')

    def __str__(self):
        return "%s. %s" % (self.code_category, self.name)

    class Meta:
        verbose_name = 'Категории'
        verbose_name_plural = 'Категории'


class Skill(models.Model):
    code_skill = models.CharField(max_length=5, verbose_name='Код навыка')
    name = models.CharField(max_length=255, verbose_name='Название навыка')
    skill_comment = models.CharField(max_length=255, null=True, blank=True, verbose_name='Комментарий к навыку')
    category = models.ForeignKey(Categories, on_delete=models.PROTECT, related_name='skill', verbose_name='Категория')
    description = models.TextField(max_length=1000, null=True, blank=True, verbose_name='Описание навыка')
    criterion = models.TextField(max_length=1000, null=True, blank=True, verbose_name='Критерии')
    difficulty = models.PositiveSmallIntegerField(default=1, verbose_name="Количество уровней сложности")
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='Время создания навыка')
    updated_date = models.DateTimeField(auto_now=True, null=True, blank=True,
                                        verbose_name='Время редактирование навыка')
    deleted_date = models.DateTimeField(null=True, blank=True, verbose_name='Время удаления навыка')

    def __str__(self):
        return "%s. %s" % (self.code_skill, self.name)

    class Meta:
        verbose_name = 'Навык'
        verbose_name_plural = 'Навыки'


class SkillsInProgram(models.Model):
    program = models.ForeignKey('Program', related_name='related_to_program', on_delete=models.PROTECT,
                                verbose_name='Программа')
    skill = models.ForeignKey('Skill', null=True, blank=True, related_name='skill_in_program', on_delete=models.PROTECT,
                              verbose_name='Навык')
    added_skill = models.CharField(max_length=1000,
                                   verbose_name='Добавленный навык', null=True,
                                   blank=True)
    added_skill_comment = models.CharField(max_length=255, null=True, blank=True,
                                           verbose_name='Комментарий к добавленному навыку')
    extra_skill_to_skill = models.ForeignKey('SkillsInProgram', related_name='extra_skill_in_program',
                                             on_delete=models.PROTECT,
                                             null=True, blank=True, verbose_name='Поднавык')
    status = models.BooleanField(default=True, verbose_name='Статус')

    def __str__(self):
        return "Навык %s" % self.id


class Program(models.Model):
    name = models.CharField(max_length=255, null=True, blank=True, verbose_name="Название программы")
    description = models.TextField(max_length=2000, blank=True, null=True, verbose_name="Описание программы")
    program_comment = models.CharField(max_length=255, null=True, blank=True, verbose_name='Комментарий к программе')
    child = models.ForeignKey('Child', on_delete=models.PROTECT, related_name='child_in_program',
                              verbose_name='Ребенок')
    author_therapist = models.ForeignKey(UserInfo, on_delete=models.PROTECT, related_name='author_program',
                                         verbose_name='Терапист')
    skills = models.ManyToManyField('Skill', through='SkillsInProgram', verbose_name='Навыки')
    status = models.BooleanField(default=True, verbose_name='Статус')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    edited_date = models.DateTimeField(auto_now=True, blank=True, null=True, verbose_name="Дата редактирования")
    deleted_date = models.DateTimeField(blank=True, null=True, verbose_name="Дата удаления")

    def __str__(self):
        return "%s %s - программа №%s" % (self.child.first_name, self.child.last_name, self.id)

    class Meta:
        verbose_name = 'Программа'
        verbose_name_plural = 'Программы'


class Session(models.Model):
    program = models.ForeignKey(Program, related_name='session_program', on_delete=models.PROTECT,
                                verbose_name='Программа')
    attending_therapist = models.ForeignKey(UserInfo, on_delete=models.PROTECT, null=True,
                                            related_name='attending_session')  # сделал временно null
    description = models.TextField(max_length=2000, blank=True, null=True, verbose_name="Описание сессии")
    created_date = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    edited_date = models.DateTimeField(auto_now=True, blank=True, null=True, verbose_name="Дата редактирования")
    deleted_date = models.DateTimeField(blank=True, null=True, verbose_name="Дата удаления")
    status_session = models.BooleanField(default=False)

    def __str__(self):
        return "Сессия %s" % self.id

    class Meta:
        verbose_name = 'Сессия'
        verbose_name_plural = 'Сессии'


class Result(models.Model):
    session = models.ForeignKey(Session, on_delete=models.SET_NULL, related_name='session_results', null=True)
    skill = models.ForeignKey(SkillsInProgram, on_delete=models.PROTECT,
                              related_name='skills_results')  # должен ссылаться на SkillInProgram
    done = models.PositiveSmallIntegerField(default=0, verbose_name="Ответил сам")
    done_with_hint = models.PositiveSmallIntegerField(default=0, verbose_name="Ответил с подсказкой")
    total = models.IntegerField(default=0)
    percent = models.IntegerField(default=0)
    created_date = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    edited_date = models.DateTimeField(auto_now=True, blank=True, null=True, verbose_name="Дата редактирования")
    deleted_date = models.DateTimeField(blank=True, null=True, verbose_name="Дата удаления")

    def __str__(self):
        return "Результаты к сессии %s" % self.session.id

    class Meta:
        verbose_name = 'Результат'
        verbose_name_plural = 'Результаты'

    def get_total(self):
        return self.done + self.done_with_hint

    def get_percent(self):
        if self.done == 0:
            self.percent = 0
        else:
            self.percent = 100 / self.get_total() * self.done
        return self.percent

    def save(self, *args, **kwargs):
        self.total = self.get_total()
        self.percent = self.get_percent()
        super(Result, self).save(*args, **kwargs)


class Test(models.Model):
    child = models.ForeignKey('Child', on_delete=models.PROTECT, related_name='child_test',
                              verbose_name='Ребенок')
    attending_therapist = models.ForeignKey(UserInfo, on_delete=models.PROTECT, null=True,
                                            related_name='attending_test')
    status = models.BooleanField(default=True, verbose_name='Статус')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    edited_date = models.DateTimeField(auto_now=True, blank=True, null=True, verbose_name="Дата редактирования")

source/webapp/views/categories.py
from django.shortcuts import get_object_or_404, redirect, render
from webapp.models import Categories
from django.views.generic import ListView, DetailView, CreateView, UpdateView, View
from webapp.forms import CategoryForm
from django.urls import reverse
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin


class CategoriesListView(LoginRequiredMixin, ListView):
    model = Categories
    template_name = 'category_views/categories_list.html'


class CategoriesDetailView(LoginRequiredMixin, DetailView):
    model = Categories
    template_name = 'category_views/categories_detail.html'


class CategoriesCreateView(LoginRequiredMixin, CreateView):
    model = Categories
    form_class = CategoryForm
    template_name = 'category_views/categories_create.html'

    def get_success_url(self):
        return reverse('webapp:categories_list')


class CategoriesUpdateView(LoginRequiredMixin, UpdateView):
    model = Categories
    template_name = 'category_views/categories_update.html'
    form_class = CategoryForm

    def get_success_url(self):
        return reverse('webapp:categories_list')


def delete_category(request, pk):
    category = get_object_or_404(Categories, pk=pk)
    category.delete()
    return redirect('webapp:categories_list')


class CategoriesSearchView(LoginRequiredMixin, View):
    template_name = 'category_views/categories_search_results.html'

    def get(self, request):
        query = self.request.GET.get('q')
        searched_categories = Categories.objects.filter(
            Q(name__icontains=query) |
            Q(code_category__icontains=query))
        context = {
            'searched_categories': searched_categories
        }
        return render(self.request, self.template_name, context)

source/webapp/templates/category_views/categories_create.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h2 class="text-center">Добавление категории</h2>
        <form action="{% url 'webapp:categories_create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group row was-validated">
                <label for="id_name" class="col-sm-2 col-form-label col-form-label-sm">Категория</label>
                <div class="col-sm-6">
                    {{ form.name }}
                    <small class="form-text text-muted">Обязательное поле</small>
                </div>
            </div>
            <div class="form-group row">
                <label for="id_code_category" class="col-sm-2 col-form-label col-form-label-sm">Код категории</label>
                <div class="col-sm-6">
                    {{ form.code_category }}
                    <small class="form-text text-muted">Желательно к заполнению</small>
                </div>
            </div>
            <button type="submit" class="btn btn-success m-2" style="width: 125px">Сохранить</button>
            <a role="button" class="btn btn-primary m-2" href="{% url 'webapp:categories_list' %}" style="width: 125px">Назад</a>
        </form>
    </div>
{% endblock %}

source/webapp/templates/category_views/categories_detail.html
{% extends 'base.html' %}
{% block title %}Навыки{% endblock %}
{% block content %}
    <div class="container">
        {#  Форма поиска категорий #}
        <div class="row mt-2 mb-3">
            <div class="block_1 col-xs-12 col-sm-6 col-lg-4">
                <div style="width: 240px">
                    <form action='{% url 'webapp:search_view_skill' %}' method="GET" accept-charset="utf-8"
                          class="form-inline my-2 my-lg-0">
                        <input class="form-control mr-2 shadow-none"
                               style="width: 67%"
                               name="q"
                               id="field"
                               value="{{ request.GET.q }}"
                               type="text"
                               placeholder="Найти навыки..."
                               aria-label="Найти...">
                        <button class="btn btn-outline-dark" type="submit" style="width: 30%">Поиск</button>
                    </form>
                </div>
                <a href="{% url 'webapp:skill_create' %}" class="btn btn-primary btn-block d-block mt-3"
                   style="width: 240px">Добавить навык</a>
            </div>
            <div class="block_2 text-center mt-4 col-xs-12 col-sm-6 col-lg-4">
                <h3>{{ categories.name }}</h3>
            </div>
        </div>
        {% for skill in categories.skill.all %}
            <div class="border-bottom">
                <div class="mt-2 mb-2">
                    <a role="button" class="text-decoration-none text-dark"
                       data-toggle="tooltip" data-placement="right" title="Нажмите для детального просмотра навыка"
                       href="{% url 'webapp:skill_detail' skill.pk %}">
                        <p class="text-wrap mb-1 font-weight-bolder"><b>{{ skill.code_skill }}</b>. {{ skill.name }}</p>
                    </a>
                    <p class="text m-0 text-truncate font-weight-normal ml-3">{{ skill.description }}</p>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}
{% block scripts %}
    <script src=../../static/js/check_find_input_is_not_null/check_find_input_is_not_null.js></script>
{% endblock %}

source/webapp/templates/category_views/categories_list.html
{% extends 'base.html' %}

{% block title %}Список категорий{% endblock %}
{% block content %}
    <div class="container">
        <div style="width: 240px">
            <form action='{% url 'webapp:search_view_categories' %}' method="GET" accept-charset="utf-8"
                  class="form-inline my-2 my-lg-0">
                <input class="form-control mr-2 shadow-none"
                       style="width: 67%"
                       name="q"
                       id="field"
                       value="{{ request.GET.q }}"
                       type="text"
                       placeholder="Найти категории..."
                       aria-label="Найти...">
                <button class="btn btn-outline-dark" type="submit" style="width: 30%">Поиск</button>

            </form>
        </div>
        <a href="{% url 'webapp:categories_create' %}" class="btn btn-primary btn-block d-block mt-3 mb-3"
           style="width: 240px">Добавить категорию</a>
        {% for categories in categories_list %}
            <div class="border-bottom pb-2 mb-1">
                <a role="button" class="text-decoration-none text-dark" style="width: 15%"
                   data-toggle="tooltip" data-placement="right" title="Нажмите для просмотра навыков в категории"
                   href="{% url 'webapp:categories_detail' categories.pk %}">
                    <p class="text-wrap d-block mb-0">{{ categories.pk }}. {{ categories.name }}</p>
                </a>
                <p class="d-block pb-0 mb-0 small font-weight-bold mt-1 ml-3">Код категории: <span
                        class="badge badge-primary">{{ categories.code_category }}</span></p>
                <a class="text-decoration-none small text-muted d-inline-block pb-0 mb-0 font-weight-light ml-3 mt-1"
                   href="{% url 'webapp:categories_update' categories.pk %}">Редактировать</a>
                <a href="#"
                   class="text-decoration-none small text-muted d-inline-block pb-0 mb-0 font-weight-light ml-1 mt-1"
                   data-toggle="modal" data-target="#deleteModal_{{ categories.pk }}" style="width: 15%"
                   data-delete-url="{% url 'webapp:categories_delete' categories.pk %}">Удалить</a>
            </div>
            <div class="modal fade" id="deleteModal_{{ categories.pk }}" tabindex="-1" role="dialog"
                 aria-labelledby="exampleModalLabel"
                 aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="card">
                            <h5 class="card-header text-center"> Удаление категории</h5>
                        </div>
                        <div class="modal-body p-0 m-0">
                            <div class="modal-body">
                                <p class="d-block text-center mb-1">Вы уверены что хотите удалить категорию
                                    <span class="d-block font-weight-bold text-center mb-3">{{ categories.name }}?</span>
                                </p>
                                <div class="text-center">
                                    <button class="category_button1_modal p-0">
                                        <a class="btn btn-outline-success"
                                           href={% url 'webapp:categories_delete' categories.pk %}>
                                            <span class="text-dark">Да</span>
                                        </a>
                                    </button>
                                    <button class="category_button2_modal p-0" data-dismiss="modal">
                                        <a class="btn btn-outline-danger"><span class="text-dark">Нет</span></a>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}
{% block scripts %}
    <script src=../../static/js/check_find_input_is_not_null/check_find_input_is_not_null.js></script>
{% endblock %}

source/webapp/templates/category_views/categories_search_results.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h3 class="mb-4 d-block">Найденных результатов: {{ searched_categories.count }}</h3>
                {% if searched_categories.count == 0 %}
                    <p class="font-weight-normal">Поиск не дал никаких результатов. Поиск позволяет искать не только по названию категории,
                но и коду категории.</p>
                    <a href="{% url 'webapp:categories_list' %}">
                        <button class="btn btn-outline-dark" type="button">Искать снова</button>
                    </a>
                {% else %}
                    {% for category in searched_categories %}
                        <div class="border-bottom">
                            <a href="{% url 'webapp:skill_detail' category.pk %}" class="text-decoration-none text-dark">
                                <p class="d-inline-block text-wrap">{{ category.code_category }}. {{ category.name }}</p>
                            </a>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

source/webapp/templates/category_views/categories_update.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h2 class="text-center">Редактирование категории</h2>
        <form action="{% url 'webapp:categories_update' form.instance.pk %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group row was-validated">
                <label for="id_name" class="col-sm-2 col-form-label col-form-label-sm">Категория</label>
                <div class="col-sm-6">
                    {{ form.name }}
                    <small class="form-text text-muted">Обязательное поле</small>
                </div>
            </div>
            <div class="form-group row">
                <label for="id_code_category" class="col-sm-2 col-form-label col-form-label-sm">Код категории</label>
                <div class="col-sm-6">
                    {{ form.code_category }}
                    <small class="form-text text-muted">Желательно к заполнению</small>
                </div>
            </div>
            <button type="submit" class="btn btn-success m-2" style="width: 125px">Сохранить</button>
            <a role="button" class="btn btn-primary -2" href="{% url 'webapp:categories_list' %}"
               style="width: 125px">Назад</a>
        </form>
    </div>
{% endblock %}