source/source/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('select2/', include('django_select2.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

source/webapp/urls.py
from django.urls import path

from webapp.views.skils import SkillDetailView, SkillUpdateView, SkillCreateView, SkillSearchView, delete_skill
from webapp.views.child import ChildList, ChildSearchView, ChildDetailView, ChildUpdateView, ChildCreateView, \
    soft_delete_child
from webapp.views.program import ProgramDetailView, ProgramListView, ProgramCreateView, ProgramUpdateView, \
    ProgramSearchView, ChildInProgramListView
from webapp.views.categories import CategoriesListView, CategoriesDetailView, CategoriesCreateView, \
    CategoriesUpdateView, CategoriesSearchView, delete_category
from webapp.views.session import create_session_and_result, AddExtraSkill, counter_get_view, counter_done, \
    counter_done_with_hint
from webapp.views.result import change_status_skill, ResultUpdateView, ResultListView, close_session_result_view

app_name = 'webapp'

urlpatterns = [
    # counter urls------------------------------------------------------------------------------------------------
    path('skill_w_hint/<int:pk>', counter_done_with_hint, name='done_w_hint'),
    path('skill_done/<int:pk>', counter_done, name='counter_done'),
    path('get_skills/<int:pk>', counter_get_view, name='counter_get_view'),
    # child urls--------------------------------------------------------------------------------------------------
    path('child/', ChildList.as_view(), name='child_list'),
    path('child_search/', ChildSearchView.as_view(), name='search_view'),
    path('child/<int:pk>', ChildDetailView.as_view(), name='child_detail'),
    path('child/create', ChildCreateView.as_view(), name='child_create'),
    path('child/<int:pk>/update', ChildUpdateView.as_view(), name='child_update'),
    path('child/<int:pk>/delete', soft_delete_child, name='child_delete'),
    # program urls------------------------------------------------------------------------------------------------
    path('', ChildInProgramListView.as_view(), name='child_program_list'),
    path('program/', ProgramListView.as_view(), name='program_list'),
    path('program_search/', ProgramSearchView.as_view(), name='search_view_program'),
    path('program/<int:pk>', ProgramDetailView.as_view(), name='program_detail'),
    path('program/create', ProgramCreateView.as_view(), name='program_create'),
    path('program/<int:pk>/update', ProgramUpdateView.as_view(), name='program_update'),
    # category urls-----------------------------------------------------------------------------------------------
    path('categories/', CategoriesListView.as_view(), name='categories_list'),
    path('categories/<int:pk>', CategoriesDetailView.as_view(), name='categories_detail'),
    path('categories/create', CategoriesCreateView.as_view(), name='categories_create'),
    path('categories/<int:pk>/update', CategoriesUpdateView.as_view(), name='categories_update'),
    path('categories/<int:pk>/delete', delete_category, name='categories_delete'),
    path('categories/categories_search/', CategoriesSearchView.as_view(), name='search_view_categories'),
    # session_urls------------------------------------------------------------------------------------------------
    path('program/<int:pk>/session', create_session_and_result, name='session_create'),
    path('program/<int:pk>/skill/create', AddExtraSkill.as_view(), name='extra_skill'),
    # result_urls------------------------------------------------------------------------------------------------
    path('session/<int:pk>/result', ResultListView.as_view(), name='session_result_view'),
    path('session/<int:pk>', close_session_result_view, name='change_status_session'),
    path('skill_in_program/<int:pk>', change_status_skill, name='change_status_skill'),
    path('session/result/<int:pk>/update', ResultUpdateView.as_view(), name='session_result_update'),
    # skill urls--------------------------------------------------------------------------------------------------
    path('skill/<int:pk>', SkillDetailView.as_view(), name='skill_detail'),
    path('skill/create', SkillCreateView.as_view(), name='skill_create'),
    path('skill/<int:pk>/update', SkillUpdateView.as_view(), name='skill_update'),
    path('skill/<int:pk>/delete', delete_skill, name='skill_delete'),
    path('skill/skill_search/', SkillSearchView.as_view(), name='search_view_skill')
]

source/webapp/models.py
from django.db import models
from django.contrib.auth.models import User


class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT, related_name='client', verbose_name='Пользователь')
    phone = models.CharField(max_length=50, verbose_name='Телефон пользователя')
    child = models.ManyToManyField('Child', related_name='user_child', verbose_name='Ребенок')
    deleted_date = models.DateTimeField(null=True, blank=True, verbose_name='Дата удаления')
    edited_date = models.DateTimeField(auto_now=True, blank=True, null=True, verbose_name='Дата редактирования')

    def __str__(self):
        return "%s" % self.user.username


class SoftDeleteManager(models.Manager):
    def active(self):
        return self.filter(is_deleted=False)

    def deleted(self):
        return self.filter(is_deleted=True)


class Child(models.Model):
    first_name = models.CharField(max_length=100, verbose_name='Имя ребенка')
    last_name = models.CharField(max_length=100, verbose_name='Фамилия ребенка')
    third_name = models.CharField(max_length=100, blank=True, null=True, verbose_name='Отчество ребенка')
    birthday = models.DateField(blank=True, null=True, verbose_name='Дата рождения')
    age = models.CharField(max_length=100, verbose_name='Возраст')
    address = models.TextField(max_length=1000, blank=True, null=True, verbose_name='Адрес проживания')
    characteristic = models.CharField(max_length=1000, blank=True, null=True, verbose_name='Характеристика на ребенка')
    preferences = models.CharField(max_length=1000, blank=True, null=True, verbose_name='Предпочтения ребенка')
    first_parent = models.CharField(max_length=255, verbose_name='Родитель')
    second_parent = models.CharField(max_length=255, blank=True, null=True, verbose_name='Второй родитель')
    contacts = models.CharField(max_length=200, blank=True, null=True, verbose_name='Контакты ребенка')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления ребенка')
    edited_date = models.DateTimeField(auto_now=True, null=True, blank=True, verbose_name='Дата редактирования')
    deleted_date = models.DateTimeField(null=True, blank=True, verbose_name='Дата удаления')
    is_deleted = models.BooleanField(default=False)

    objects = SoftDeleteManager()

    def __str__(self):
        return "%s %s" % (self.first_name, self.last_name)

    class Meta:
        verbose_name = 'Дети'
        verbose_name_plural = 'Дети'


class Categories(models.Model):
    name = models.CharField(max_length=255, verbose_name='Название категории')
    code_category = models.CharField(max_length=50, null=True, blank=True, verbose_name='Код категории')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')
    edited_date = models.DateTimeField(auto_now=True, null=True, blank=True, verbose_name='Время редактирования')
    deleted_date = models.DateTimeField(null=True, blank=True, verbose_name='Время удаления')

    def __str__(self):
        return "%s. %s" % (self.code_category, self.name)

    class Meta:
        verbose_name = 'Категории'
        verbose_name_plural = 'Категории'


class Skill(models.Model):
    code_skill = models.CharField(max_length=5, verbose_name='Код навыка')
    name = models.CharField(max_length=255, verbose_name='Название навыка')
    skill_comment = models.CharField(max_length=255, null=True, blank=True, verbose_name='Комментарий к навыку')
    category = models.ForeignKey(Categories, on_delete=models.PROTECT, related_name='skill', verbose_name='Категория')
    description = models.TextField(max_length=1000, null=True, blank=True, verbose_name='Описание навыка')
    criterion = models.TextField(max_length=1000, null=True, blank=True, verbose_name='Критерии')
    difficulty = models.PositiveSmallIntegerField(default=1, verbose_name="Количество уровней сложности")
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='Время создания навыка')
    updated_date = models.DateTimeField(auto_now=True, null=True, blank=True,
                                        verbose_name='Время редактирование навыка')
    deleted_date = models.DateTimeField(null=True, blank=True, verbose_name='Время удаления навыка')

    def __str__(self):
        return "%s. %s" % (self.code_skill, self.name)

    class Meta:
        verbose_name = 'Навык'
        verbose_name_plural = 'Навыки'


class SkillsInProgram(models.Model):
    program = models.ForeignKey('Program', related_name='related_to_program', on_delete=models.PROTECT,
                                verbose_name='Программа')
    skill = models.ForeignKey('Skill', null=True, blank=True, related_name='skill_in_program', on_delete=models.PROTECT,
                              verbose_name='Навык')
    added_skill = models.CharField(max_length=1000,
                                   verbose_name='Добавленный навык', null=True,
                                   blank=True)
    added_skill_comment = models.CharField(max_length=255, null=True, blank=True,
                                           verbose_name='Комментарий к добавленному навыку')
    extra_skill_to_skill = models.ForeignKey('SkillsInProgram', related_name='extra_skill_in_program',
                                             on_delete=models.PROTECT,
                                             null=True, blank=True, verbose_name='Поднавык')
    status = models.BooleanField(default=True, verbose_name='Статус')

    def __str__(self):
        return "Навык %s" % self.id


class Program(models.Model):
    name = models.CharField(max_length=255, null=True, blank=True, verbose_name="Название программы")
    description = models.TextField(max_length=2000, blank=True, null=True, verbose_name="Описание программы")
    program_comment = models.CharField(max_length=255, null=True, blank=True, verbose_name='Комментарий к программе')
    child = models.ForeignKey('Child', on_delete=models.PROTECT, related_name='child_in_program',
                              verbose_name='Ребенок')
    author_therapist = models.ForeignKey(UserInfo, on_delete=models.PROTECT, related_name='author_program',
                                         verbose_name='Терапист')
    skills = models.ManyToManyField('Skill', through='SkillsInProgram', verbose_name='Навыки')
    status = models.BooleanField(default=True, verbose_name='Статус')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    edited_date = models.DateTimeField(auto_now=True, blank=True, null=True, verbose_name="Дата редактирования")
    deleted_date = models.DateTimeField(blank=True, null=True, verbose_name="Дата удаления")

    def __str__(self):
        return "%s %s - программа №%s" % (self.child.first_name, self.child.last_name, self.id)

    class Meta:
        verbose_name = 'Программа'
        verbose_name_plural = 'Программы'


class Session(models.Model):
    program = models.ForeignKey(Program, related_name='session_program', on_delete=models.PROTECT,
                                verbose_name='Программа')
    attending_therapist = models.ForeignKey(UserInfo, on_delete=models.PROTECT, null=True,
                                            related_name='attending_session')  # сделал временно null
    description = models.TextField(max_length=2000, blank=True, null=True, verbose_name="Описание сессии")
    created_date = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    edited_date = models.DateTimeField(auto_now=True, blank=True, null=True, verbose_name="Дата редактирования")
    deleted_date = models.DateTimeField(blank=True, null=True, verbose_name="Дата удаления")
    status_session = models.BooleanField(default=False)

    def __str__(self):
        return "Сессия %s" % self.id

    class Meta:
        verbose_name = 'Сессия'
        verbose_name_plural = 'Сессии'


class Result(models.Model):
    session = models.ForeignKey(Session, on_delete=models.SET_NULL, related_name='session_results', null=True)
    skill = models.ForeignKey(SkillsInProgram, on_delete=models.PROTECT,
                              related_name='skills_results')  # должен ссылаться на SkillInProgram
    done = models.PositiveSmallIntegerField(default=0, verbose_name="Ответил сам")
    done_with_hint = models.PositiveSmallIntegerField(default=0, verbose_name="Ответил с подсказкой")
    total = models.IntegerField(default=0)
    percent = models.IntegerField(default=0)
    created_date = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    edited_date = models.DateTimeField(auto_now=True, blank=True, null=True, verbose_name="Дата редактирования")
    deleted_date = models.DateTimeField(blank=True, null=True, verbose_name="Дата удаления")

    def __str__(self):
        return "Результаты к сессии %s" % self.session.id

    class Meta:
        verbose_name = 'Результат'
        verbose_name_plural = 'Результаты'

    def get_total(self):
        return self.done + self.done_with_hint

    def get_percent(self):
        if self.done == 0:
            self.percent = 0
        else:
            self.percent = 100 / self.get_total() * self.done
        return self.percent

    def save(self, *args, **kwargs):
        self.total = self.get_total()
        self.percent = self.get_percent()
        super(Result, self).save(*args, **kwargs)


class Test(models.Model):
    child = models.ForeignKey('Child', on_delete=models.PROTECT, related_name='child_test',
                              verbose_name='Ребенок')
    attending_therapist = models.ForeignKey(UserInfo, on_delete=models.PROTECT, null=True,
                                            related_name='attending_test')
    status = models.BooleanField(default=True, verbose_name='Статус')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    edited_date = models.DateTimeField(auto_now=True, blank=True, null=True, verbose_name="Дата редактирования")

source/webapp/views/categories.py
from django.shortcuts import get_object_or_404, redirect, render
from webapp.models import Categories
from django.views.generic import ListView, DetailView, CreateView, UpdateView, View
from webapp.forms import CategoryForm
from django.urls import reverse
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin


class CategoriesListView(LoginRequiredMixin, ListView):
    model = Categories
    template_name = 'category_views/categories_list.html'


class CategoriesDetailView(LoginRequiredMixin, DetailView):
    model = Categories
    template_name = 'category_views/categories_detail.html'


class CategoriesCreateView(LoginRequiredMixin, CreateView):
    model = Categories
    form_class = CategoryForm
    template_name = 'category_views/categories_create.html'

    def get_success_url(self):
        return reverse('webapp:categories_list')


class CategoriesUpdateView(LoginRequiredMixin, UpdateView):
    model = Categories
    template_name = 'category_views/categories_update.html'
    form_class = CategoryForm

    def get_success_url(self):
        return reverse('webapp:categories_list')


def delete_category(request, pk):
    category = get_object_or_404(Categories, pk=pk)
    category.delete()
    return redirect('webapp:categories_list')


class CategoriesSearchView(LoginRequiredMixin, View):
    template_name = 'category_views/categories_search_results.html'

    def get(self, request):
        query = self.request.GET.get('q')
        searched_categories = Categories.objects.filter(
            Q(name__icontains=query) |
            Q(code_category__icontains=query))
        context = {
            'searched_categories': searched_categories
        }
        return render(self.request, self.template_name, context)

source/webapp/templates/program_views/program_create.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block styles %}
    {{ form.media.css }}
{% endblock %}
{% block content %}
    <div class="container">
        <h2 class="text-center">Добавление программы</h2>
        <form action="{% url 'webapp:program_create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group row">
                <label for="id_name" class="col-sm-2 col-form-label col-form-label-sm">Программа</label>
                <div class="col-sm-6">
                    {{ form.name }}
                    <small class="form-text text-muted">Желательно ввести название для программы</small>
                </div>
            </div>
            <div class="form-group row was-validated">
                <label for="id_child" class="col-sm-2 col-form-label col-form-label-sm">Ребенок</label>
                <div class="col-sm-6">
                    {{ form.child }}
                    <small class="form-text text-muted">Обязательное поле</small>
                </div>
            </div>
            <div class="form-group row was-validated">
                <label for="id_author_therapist" class="col-sm-2 col-form-label col-form-label-sm">Терапевт:</label>
                <div class="col-sm-6">
                    {{ form.author_therapist }}
                    <small class="form-text text-muted">Обязательное поле</small>
                </div>
            </div>
            <div class="form-group row">
                <label for="id_description" class="col-sm-2 col-form-label col-form-label-sm">Описание</label>
                <div class="col-sm-6">
                    {{ form.description }}
                    <small class="form-text text-muted">По желанию</small>
                </div>
            </div>
            <div class="form-group row">
                <label for="id_program_comment" class="col-sm-2 col-form-label col-form-label-sm">Комментарий к
                    программе</label>
                <div class="col-sm-6">
                    {{ form.program_comment }}
                    <small class="form-text text-muted">По желанию</small>
                </div>
            </div>
            <div class="form-group row">
                <label for="id_skills" class="col-sm-2 col-form-label col-form-label-sm">Навыки</label>
                <div class="col-sm-6">
                    {{ form.skills }}
                </div>
            </div>
            <button type="submit" class="btn btn-success m-2" style="width: 125px">Сохранить</button>
            <a role="button" class="btn btn-primary m-2" href="{% url 'webapp:program_list' %}" style="width: 125px">Назад</a>
        </form>
    </div>
{% endblock %}
{% block scripts %}
    {{ form.media.js }}
{% endblock %}

source/webapp/templates/program_views/program_detail.html
{% extends 'base.html' %}
{% block title %}Детали программы{% endblock %}
{% block content %}
    <div class="container">
        {% if program.status == True %}
            <h2 class="text-center">Программа действующая</h2>
        {% else %}
            <h2 class="text-center">Программа закрыта</h2>
        {% endif %}

        {% if program.name %}
            <p class="font-weight-bold">Программа: <span class="font-weight-normal">{{ program.name }}</span></p>
        {% else %}
            <p class="font-weight-bold">Программа: <span
                    class="font-weight-normal">Название программы отсутствует</span></p>
        {% endif %}

        {% if program.description %}
            <p class="font-weight-bold">Описание: <span class="font-weight-normal">{{ program.description }}</span>
            </p>
        {% else %}
            <p class="font-weight-bold">Описание: <span
                    class="font-weight-normal">Описание программы отсутствует</span></p>
        {% endif %}

        {% if program.program_comment %}
            <p class="font-weight-bold">Комментарий: <span
                    class="font-weight-normal">{{ program.program_comment }}</span>
            </p>
        {% else %}
            <p class="font-weight-bold">Комментарий: <span
                    class="font-weight-normal">Комментарий к программе отсутствует</span></p>
        {% endif %}


        {% if program.child.third_name %}
            <p class="font-weight-bold">Ребенок: <span
                    class="font-weight-normal">{{ program.child.last_name }} {{ program.child.first_name }} {{ program.child.third_name }}</span>
            </p>
        {% else %}
            <p class="font-weight-bold">Ребенок: <span
                    class="font-weight-normal">{{ program.child.last_name }} {{ program.child.first_name }}</span>
            </p>
        {% endif %}

        <p class="font-weight-bold">Автор: <span
                class="font-weight-normal">{{ program.author_therapist.user }}</span>
        </p>

        <p class="font-weight-bold">Дата создания: <span
                class="font-weight-normal">{{ program.created_date.date }}</span></p>

        <p class="font-weight-bold">Дата последнего редактирования: <span
                class="font-weight-normal">{{ program.edited_date.date }}</span></p>

        <div class="accordion" id="accordionExample">
            <div class="card">
                <button class="btn btn_outline_none btn-light"
                        type="button"
                        data-toggle="collapse"
                        data-target="#collapseOne"
                        aria-controls="collapseOne">
                    <span class="btn_accordion_text">Все навыки в программе</span>
                </button>
                <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
                    <h5 id="no_session" class="text-dark text-center m-0 pl-5"></h5>
                    <div id="table_1" class="table m-0 table_skill">
                        <table class="col-12 table table-bordered m-0 p-0">
                            <thead>
                            <tr class="text-center">
                                <th scope="col">Название</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for program_skill in program.related_to_program.all %}
                                <tr>
                                    <td id="is_there_skills"><p class="text m-0 text-truncate font-weight-normal">
                                        {{ program_skill.skill.code_skill }}
                                        | {{ program_skill.skill.name }}</p>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="card">
                <button class="btn btn_outline_none btn-light"
                        type="button"
                        data-toggle="collapse"
                        data-target="#collapseTwo"
                        aria-controls="collapseTwo">
                    <span class="btn_accordion_text">Закрытые навыки в программе</span>
                </button>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                    <h5 id="close_skill" class="text-dark text-center m-0 pl-5"></h5>
                    <div id="table_2" class="table m-0 table_skill">
                        <table class="col-12 table table-bordered m-0 p-0">
                            <thead>
                            <tr class="text-center">
                                <th scope="col">Название</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for program_skill in program.related_to_program.all %}
                                {% if program_skill.status == False %}
                                    <tr>
                                        <td id="is_there_close_skill">
                                            <p class="text m-0 text-truncate font-weight-normal">
                                                {{ program_skill.skill.code_skill }}
                                                | {{ program_skill.skill.name }}</p>
                                        </td>
                                    </tr>
                                {% endif %}
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="card">
                <button class="btn btn_outline_none btn-light"
                        type="button"
                        data-toggle="collapse"
                        data-target="#collapseThree"
                        aria-controls="collapseThree">
                    <span class="btn_accordion_text">Открытые навыки в программе</span>
                </button>
                <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
                    <h5 id="open_skill" class="text-dark text-center m-0 pl-5"></h5>
                    <div id="table_3" class="table m-0 table_skill">
                        <table class="col-12 table table-bordered m-0">
                            {% if all_skill.values %}
                                <thead>
                                <tr class="text-center">
                                    <th scope="col">Название</th>
                                    <th scope="col">Процент</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for skill, percent in all_skill.items %}
                                    <tr class="text-left">
                                        <td id="is_there_open_skill">{{ skill }}</td>
                                        <td class="text-center">{{ percent }}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            {% endif %}
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="text-center mt-4">
            {% if program.status == True %}
                <a role="button" class="btn btn-success m-2 update_and_back"
                   href={% url 'webapp:program_update' program.pk %}>Редактировать</a>
            {% endif %}
            <a role="button" class="btn btn-primary m-2 update_and_back"
               href="{% url 'webapp:program_list' %}">Назад</a>
        </div>
        <h3 class="text-center mt-4">Результаты по сессиям</h3>
        <h4 id="session" class="text-dark font-weight-normal text-center mt-3"></h4>
        <div class="row justify-content-center">
            {% for session in program.session_program.all %}
                <div id="is_there_session" class="col-11 col-sm-5 col-md-3 col-lg-2 m-1 p-0">
                    <div class="card-header text-center"><b>Сессия <br> {{ session.created_date.date }}</b></div>
                    <div class="card-body text-center p-0 m-0 result">
                        <a href="{% url 'webapp:session_result_view' session.pk %}"
                           class="btn btn-block btn-primary m-0">Результат</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}
{% block scripts %}
    <script src=../../static/js/program_detail/check_skill.js></script>
{% endblock %}

source/webapp/templates/program_views/program_update.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block styles %}
    {{ form.media.css }}
{% endblock %}
{% block content %}
    <div class="container">
        <h2 class="text-center">Редактирование программы</h2>
        <form action="{% url 'webapp:program_update' form.instance.pk %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group row">
                <label for="id_name" class="col-sm-2 col-form-label col-form-label-sm">Программа</label>
                <div class="col-sm-6">
                    {{ form.name }}
                    <small class="form-text text-muted">Желательно ввести название для программы</small>
                </div>
            </div>
            <div class="form-group row was-validated">
                <label for="id_child" class="col-sm-2 col-form-label col-form-label-sm">Ребенок</label>
                <div class="col-sm-6">
                    {{ form.child }}
                    <small class="form-text text-muted">Обязательное поле</small>
                </div>
            </div>
            <div class="form-group row was-validated">
                <label for="id_author_therapist" class="col-sm-2 col-form-label col-form-label-sm">Терапевт:</label>
                <div class="col-sm-6">
                    {{ form.author_therapist }}
                    <small class="form-text text-muted">Обязательное поле</small>
                </div>
            </div>
            <div class="form-group row">
                <label for="id_description" class="col-sm-2 col-form-label col-form-label-sm">Описание</label>
                <div class="col-sm-6">
                    {{ form.description }}
                    <small class="form-text text-muted">По желанию</small>
                </div>
            </div>
            <div class="form-group row">
                <label for="id_program_comment" class="col-sm-2 col-form-label col-form-label-sm">Комментарий к
                    программе</label>
                <div class="col-sm-6">
                    {{ form.program_comment }}
                    <small class="form-text text-muted">По желанию</small>
                </div>
            </div>
            <div class="form-group row">
                <label for="id_skills" class="col-sm-2 col-form-label col-form-label-sm">Навыки</label>
                <div class="col-sm-6">
                    {{ form.skills }}
                </div>
            </div>
            <button type="submit" class="btn btn-success m-2" style="width: 125px">Сохранить</button>
            <a role="button" class="btn btn-primary m-2" href="{{ request.META.HTTP_REFERER }}"
               style="width: 125px">Назад</a>
        </form>
    </div>
{% endblock %}
{% block scripts %}
    {{ form.media.js }}
{% endblock %}